#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument, displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed, and ping the IP 5 times
if [ ! "$1" ]
then
    echo "Usage: ${0:2} {IP_ADDRESS}"
else
    ping -c5 "$1"
fi
